name: build1

on: 
  push:
    paths: 
      - build/**
      - .github/workflows/build.yml

jobs:
  windows:
    runs-on: windows-2016

    steps:
      - uses: actions/checkout@v2
      
      - name: Insatll MSVC
        uses: microsoft/setup-msbuild@v1.0.2
      
      - name: Build
        run: |
          cd build
          .\make_win_lua54.bat
          .\make_win32_lua53.bat
          .\make_win64_lua53.bat
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build Luajit
        run: |
          cd build
          .\make_win64_luajit.bat
      - name: Build Luac
        run: |
          cd build
          cd luac
          .\make_win64.bat
          .\make_win32.bat
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_lua54/**/*
          name: plugin_lua54
      - name: Upload53
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_lua53/**/*
          name: plugin_lua53   
      - name: UploadJit
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_luajit/**/*
          name: plugin_luajit
      - name: UploadLuacWin32
        uses: actions/upload-artifact@v2
        with:
          path: ./build/luac/build32/Release/**/*
          name: build32
      - name: UploadLuacWin64
        uses: actions/upload-artifact@v2
        with:
          path: ./build/luac/build64/Release/**/*
          name: build64 
    

   
